import type { Metadata } from "next";
import { BookingInvitation, Eyebrow, FeatureImage, PageIntro, TextLink } from "@/components/shared";
import { gallery } from "@/data/site";

export const metadata: Metadata = { title: "The Chef", description: "Meet Mara Tan, the fictional chef behind the EMBER concept." };
export default function ChefPage() {
  return <main id="main"><PageIntro kicker="THE CHEF · FICTIONAL PROFILE" title="A patient hand. An open flame." lead="Mara Tan is the imagined culinary voice behind EMBER: curious about ingredients, attentive to fire, and always happiest when a table is full." />
    <section className="wrap chef-profile section-pad"><div className="chef-profile-image"><FeatureImage image={gallery[4]} /></div><div className="chef-profile-copy"><Eyebrow>MARA TAN / CONCEPT CHARACTER</Eyebrow><h2 className="section-title">The beauty is<br /><em>in the attention.</em></h2><p>For Mara, live-fire cooking is an exercise in listening. Every ingredient responds differently to heat; the pleasure lies in finding its moment. Her imagined menu moves comfortably between vegetables, fish, and the grill, always with the same respect for texture and balance.</p><blockquote>“I want people to remember how they felt at the table, not just what was on it.”</blockquote><p className="concept-aside">This chef, biography and quotation are original fictional content for a portfolio concept.</p></div></section>
    <section className="chef-philosophy section-pad"><div className="wrap"><Eyebrow light>THREE THINGS WE BELIEVE</Eyebrow><div className="philosophy-grid"><div><span>01</span><h3>Follow the season</h3><p>Let what is best right now lead the conversation.</p></div><div><span>02</span><h3>Respect the fire</h3><p>Use heat with intention, never just for spectacle.</p></div><div><span>03</span><h3>Make room for people</h3><p>The meal belongs to everyone around the table.</p></div></div></div></section>
    <section className="wrap chef-detail section-pad"><FeatureImage image={gallery[1]} /><div><Eyebrow>FROM THE HEARTH</Eyebrow><h2 className="section-title">One ingredient.<br /><em>Many possibilities.</em></h2><p>Take the oyster mushroom: deeply savoury after the flame, soft against fermented cream, lifted by fresh herbs. A little contrast can make a familiar ingredient feel new again.</p><TextLink href="/menu">Explore the menu</TextLink></div></section><BookingInvitation /></main>;
}
